### ISSUE TITLE
Confused 

### ISSUE THREAD

**Issue by Schwartz02** [klinker24/google-calendar-desktop#2]
Can u make a more detailed set of instructions. Its just very confusing as to where to do what and where what is...

**Comment by klinker24** [comment]
If you have specific questions, feel free to ask them. I do not know what you need more instructions for. 

Building this app requires a standard JavaScript development environment. This isn't something that I will walk you through setting up. There are countless tutorials on the internet for setting up node/npm/yarn. Once you have those set up, my instructions are pretty explicit. 

This repo is not a tutorial for JS development or electron. I would recommend looking elsewhere if you are just trying to learn more about the technologies. There are many resources available for something like that. This repo is a simple example of one way that you can use electron to display a webpage.
