### ISSUE TITLE
problem with  calendar-1.6.0.zip

### ISSUE THREAD

**Issue by cmssghub** [klinker24/google-calendar-desktop#3]
Hello
I am new to github and programming.

I've been using your application on Windows 10 for the last few months (since v 1.3) and I think it's very good and perfect to have on the desktop.

Today I remembered to see if there was a newer version and found v1.6.0. After downloading I tried to open the zip and give me a "Windows can't open the folder".

Can you create a new zip so that I can install this new version.

Thanks
Miguel

**Comment by klinker24** [comment]
The zip file is not for Windows. This is the latest version of the Windows app, but I don't plan to continue building the Windows app.

https://github.com/klinker24/google-calendar-desktop/releases/download/v1.4.1/calendar-1.4.1.exe

It is just a web wrapper, the new versions are not going to give you any additional functionality. They are simply upgrades for electron.

**Comment by cmssghub** [comment]
OK
Thank you for the quick response.
