### ISSUE TITLE
Login prevented "can't keep your account secure"

### ISSUE THREAD

**Issue by bmitchinson** [klinker24/google-calendar-desktop#4]
Thanks for always keeping this up to date with new versions of electron, I use it on multiple machines.

When logging in with 2FA enabled google account I'm given this message :(

![image](https://user-images.githubusercontent.com/33632286/70365380-b9b32180-1856-11ea-992d-ecdca8c4b818.png)

Using the newest release, 1.6.1, on OSX 10.15
Haven't tried building my own but don't anticipate that solving the issue

**Comment by klinker24** [comment]
I really have no idea on this, sorry. I use 2FA with my Google account too and have not seen any problems.

**Comment by klinker24** [comment]
I did run across some threads having issues with this on Electron. Looks like I just needed to remove "Electron" from the user agent. I have done that and will publish a new version to test.

**Comment by bmitchinson** [comment]
Amazing! Looking forward to having this back, thank you.
